export const LOAD_USER_RATINGS_SUCCESS = "LOAD_USER_RATINGS_SUCCESS";
// export const LOAD_USER_RATINGS_SUCCESS = "LOAD_USER_RATINGS_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
